### ISSUE TITLE
Git get fail, could not clone

### ISSUE THREAD

**Issue by zhongqingsong** [Aidan63/haxe-discord_rpc-externs#2]
hello, I use the cmd in the README.md  "haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc"
it is no response, and report message:
Error: Could not clone Git repository.

By the way, I can clone the other project, so seems like not my Git's error.  And anyone know how to deal with this?

**Comment by Aidan63** [comment]
Hello, I don't think this is an issue with the library and the error you've given is very vague (not to mention you haven't said what this "other project" is). If you google haxelib along with that error message you'll find many result (quite a few specific to this very lib) which should fix your problem.
