### ISSUE TITLE
This takes soooo long and another problem. sorry Aidan63 :(

### ISSUE THREAD

**Issue by DaBlueNinja03** [Aidan63/haxe-discord_rpc-externs#3]
whenever i try to update discord_RPC, its like it doesnt even update, it just says `You already have Discord_RPC version git installed
Updating Discord_RPC version git ...` PLEASE HELP MEH

**Comment by DaBlueNinja03** [comment]
The same thing happens with polymod

**Comment by Aidan63** [comment]
If there is an issue here it will be related to your setup and not this library.

**Comment by DaBlueNinja03** [comment]
then how do i get it so it doesnt take forever, sorry if im being a bug

**Comment by Aidan63** [comment]
You haven't explained what "This takes soooo long" actually means (I haven't the slightest clue), and it doesn't help that you then seem to talk about an equally vague completely unrelated issue in the description. If you don't explain in detail what you're trying to do and what you've actually done no one can help you.
