### ISSUE TITLE
pathspec

### ISSUE THREAD

**Issue by greplol** [Aidan63/haxe-discord_rpc-externs#5]
it says
You already have discord_rpc version git installed.
Updating discord_rpc version git ...
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
fix it

**Comment by Aidan63** [comment]
You've got to atleast say what you're trying to do and what command you've entered if you want any help...

> fix it

And if thats the sort of attitude you have, I'm not particually interested in helping you with your problem.

**Comment by greplol** [comment]
i entered: git discord_rpc https://github.com/Aidan63/linc_discord-rpc

**Comment by greplol** [comment]
and im sorry im stressed of compiling fnf source code
