### ISSUE TITLE
New Suggestion: Add Modern Discord RPC features

### ISSUE THREAD

**Issue by DamianBossPL** [Aidan63/haxe-discord_rpc-externs#6]
This Repository has been updated 5 months ago. And I think it needs an update.
You should add buttons

It could really help other people you know. For example:

- `Download like for a game`
- `Documentation for coding`
- `etc...`

**Comment by Aidan63** [comment]
I'm not sure what you mean, are you talking about more features in the library or documentation?

In either case the underlying discord-rpc library has been depricated and I don't use this library any more so I'm not planning on doing any work (features or documentation) on it.

**Comment by DamianBossPL** [comment]
> I'm not sure what you mean, are you talking about more features in the library or documentation?
> 
> In either case the underlying discord-rpc library has been depricated and I don't use this library any more so I'm not planning on doing any work (features or documentation) on it.

I'm talking about updating the library to support Discord Presence Buttons.

**Comment by Aidan63** [comment]
The old discord-rpc library doesn't seem to support buttons outside of game invites. I'm guessing that functionality was added in the newer discord game SDK which this library doesn't provide bindings for.
